export const events = [
  {
    title: "Cloud Native AI + Inference Day",
    image: "/images/event1.png",
    slug: "cloud-native-ai-inference-day-2026",
    location: "Salt Palace Convention Center, Salt Lake City, UT",
    date: "November 9, 2026",
    time: "9:00 AM MST",
  },
  {
    title: "KubeCon + CloudNativeCon North America",
    image: "/images/event2.png",
    slug: "kubecon-cloudnativecon-north-america-2026",
    location: "Salt Palace Convention Center, Salt Lake City, UT",
    date: "November 9-12, 2026",
    time: "8:00 AM MST",
  },
  {
    title: "React Summit New York",
    image: "/images/event3.png",
    slug: "react-summit-new-york-2026",
    location: "New York, NY",
    date: "November 17 & 20, 2026",
    time: "9:00 AM EST",
  },
  {
    title: "AWS re:Invent",
    image: "/images/event4.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV",
    date: "November 30-December 4, 2026",
    time: "8:00 AM PST",
  },
  {
    title: "KubeCon + CloudNativeCon Europe",
    image: "/images/event5.png",
    slug: "kubecon-cloudnativecon-europe-2027",
    location: "Barcelona, Spain",
    date: "March 15-18, 2027",
    time: "9:00 AM CET",
  },
  {
    title: "React Summit Amsterdam",
    image: "/images/event6.png",
    slug: "react-summit-amsterdam-2027",
    location: "Amsterdam, Netherlands",
    date: "May 21 & 25, 2027",
    time: "9:00 AM CEST",
  },
];
